esphome:
    name: garage-door
    comment: Garage door opener

esp32:
    board: nodemcu-32s

logger:
    level: DEBUG

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    power_save_mode: none
