esphome:
    name: garage-door
    comment: Garage door opener

esp32:
    board: nodemcu-32s

logger:
    level: DEBUG

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    domain: !secret local_domain
    power_save_mode: none

ota:
    password: !secret ota_password
    port: !secret ota_port

api:
    port: !secret api_port
    encryption:
        key: !secret api_key

# Garage door status
binary_sensor:
    - platform: gpio
      device_class: GARAGE_DOOR
      name: Garage Door Status
      pin:
          number: 16
          inverted: true
          mode:
              input: true
              pullup: false
              pulldown: true

# Toogle garage door
output:
    - platform: gpio
      pin: 17
      id: garage_door_activate

button:
    - platform: output
      name: Garage Door
      output: garage_door_activate
      duration: 100ms
